import tkinter as tk
from tkinter import ttk
def on_click():
	txtEntry.configure(text="1"+name.get())
	boton.configure(state='1')
pass
win=tk.Tk()
win.title("Calculadora")
win.resizable(1,1)
label1=ttk.Label(win,text="Calculadora")
label1.grid(row=1,column=2)
boton=ttk.Button(win,text="1",command=botonon_click)
boton.grid(row=4,column=0)
boton2=ttk.Button(win,text="2",command=on_click)
boton2.grid(row=4,column=1)
boton3=ttk.Button(win,text="3",command=on_click)
boton3.grid(row=4,column=2)
boton4=ttk.Button(win,text="4",command=on_click)
boton4.grid(row=5,column=0)
boton5=ttk.Button(win,text="5",command=on_click)
boton5.grid(row=5,column=1)
boton6=ttk.Button(win,text="6",command=on_click)
boton6.grid(row=5,column=2)
boton7=ttk.Button(win,text="7",command=on_click)
boton7.grid(row=6,column=0)
boton8=ttk.Button(win,text="8",command=on_click)
boton8.grid(row=6,column=1)
boton9=ttk.Button(win,text="9",command=on_click)
boton9.grid(row=6,column=2)
boton10=ttk.Button(win,text="0",command=on_click)
boton10.grid(row=7,column=1)
boton11=ttk.Button(win,text=".",command=on_click)
boton11.grid(row=7,column=2)
boton12=ttk.Button(win,text="/",command=on_click)
boton12.grid(row=4,column=3)
boton13=ttk.Button(win,text="X",command=on_click)
boton13.grid(row=5,column=3)
boton14=ttk.Button(win,text="-",command=on_click)
boton14.grid(row=6,column=3)
boton14=ttk.Button(win,text="+",command=on_click)
boton14.grid(row=7,column=3)
boton15=ttk.Button(win,text="=",command=on_click)
boton15.grid(row=8,column=3)
boton16=ttk.Button(win,text="CE",command=on_click)
boton16.grid(row=7,column=0)

name=tk.StringVar()
txtEntry=ttk.Entry(win,textvariable=name)
txtEntry.grid(row=2,column=3)

win.mainloop()
